export enum Env {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',

  CORS_ORIGIN = 'CORS_ORIGIN',
  CORS_METHODS = 'CORS_METHODS',

  DATABASE_URL = 'DATABASE_URL',

  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_MS = 'JWT_ACCESS_TOKEN_EXPIRATION_MS',

  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_MS = 'JWT_REFRESH_TOKEN_EXPIRATION_MS',

  JWT_RESET_TOKEN_SECRET = 'JWT_RESET_TOKEN_SECRET',
  JWT_RESET_TOKEN_EXPIRATION_MS = 'JWT_RESET_TOKEN_EXPIRATION_MS',

  GOOGLE_WEB_CLIENT_ID = 'GOOGLE_WEB_CLIENT_ID',
  GOOGLE_WEB_CLIENT_SECRET = 'GOOGLE_WEB_CLIENT_SECRET',
  GOOGLE_WEB_CALLBACK_URL = 'GOOGLE_WEB_CALLBACK_URL',
  GOOGLE_ANDROID_CLIENT_ID = 'GOOGLE_ANDROID_CLIENT_ID',
  GOOGLE_IOS_CLIENT_ID = 'GOOGLE_IOS_CLIENT_ID',
}
