export enum Env {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',

  CORS_ORIGIN = 'CORS_ORIGIN',
  CORS_METHODS = 'CORS_METHODS',

  DATABASE_URL = 'DATABASE_URL',

  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_MS = 'JWT_ACCESS_TOKEN_EXPIRATION_MS',

  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_MS = 'JWT_REFRESH_TOKEN_EXPIRATION_MS',

  JWT_RESET_TOKEN_SECRET = 'JWT_RESET_TOKEN_SECRET',
  JWT_RESET_TOKEN_EXPIRATION_MS = 'JWT_RESET_TOKEN_EXPIRATION_MS',
}
